/**
 * Content
 * (sails.config.content)
 *
 * Localized UI strings and page copy for the SLOU storefront.
 * Supported locales: lt (default), en, pt, fr, de, es, it.
 * Selected per request via the `locale` policy and switched through the
 * /kalba/:locale route.
 *
 * NOTE: whenever new user-facing text is added, translate it into ALL locales
 * below (keep every locale in sync).
 */

module.exports.content = {

  lt: {
    langLabel: 'LT', htmlLang: 'lt-LT',
    topbar: 'Rankų darbo · Augalinio rauginimo oda · Gaminama Lietuvoje',
    nav: { home: 'Pradžia', shop: 'Parduotuvė', contacts: 'Kontaktai' },
    titles: { home: 'SLOU — rankinės, raktų aksesuarai, piniginės', shop: 'Parduotuvė — SLOU', contacts: 'Kontaktai — SLOU', returns: 'Pristatymo ir grąžinimo sąlygos — SLOU', privacy: 'Privatumo politika — SLOU', cookies: 'Slapukų politika — SLOU' },
    hero: { eyebrow: 'Rankų darbo oda', title: 'Daiktai, gimstantys iš lėto', tag: 'rankinės · raktų aksesuarai · piniginės', lead: 'Kiekvienas SLOU gaminys – tai rankomis sukurtas daiktas iš natūralios, augaliniu būdu raugintos odos. Ne skubant, o įdėmiai.', cta: 'Apžiūrėti parduotuvę' },
    features: [ { t: 'Rankų darbo', d: 'Kiekviena detalė siūta ir formuota rankomis.' }, { t: 'Augalinio rauginimo oda', d: 'Natūrali, sensta gražiai, įgauna patiną.' }, { t: 'Be pamušalo', d: 'Minimalistinė, tvari konstrukcija.' }, { t: 'Gaminama po užsakymo', d: 'Iki 7–14 darbo dienų, Lietuvoje.' } ],
    shop: { eyebrow: 'Kolekcija', title: 'Parduotuvė', sub: 'Rankomis siūti gaminiai kasdienai.', subLong: 'Rankomis siūti gaminiai iš augalinio rauginimo odos, gaminami po užsakymo.', all: 'Visos prekės' },
    ctaband: { title: 'Turite klausimų?', text: 'Norite pasitarti dėl gaminio ar užsisakyti individualų sprendimą? Parašykite – atsakysiu kuo greičiau.', cta: 'Susisiekti' },
    videos: { sound: 'Įjungti / išjungti garsą', play: 'Groti vaizdo įrašą', progress: 'Vaizdo įrašo eiga', full: 'Visas ekranas' },
    order: { eyebrow: 'Užsakymas', title: 'Sukurkite savo užsakymą', lead: 'Aprašykite, ko norėtumėte: gaminį, odos spalvą, dydį, graviūrą ar visai savitą sprendimą. Atsakysiu čia, šioje svetainėje. Sugrįžę mūsų pokalbį matysite puslapio viršuje.', name: 'Vardas', email: 'El. paštas (nebūtinas)', details: 'Jūsų užsakymas', placeholder: 'Pavyzdžiui: norėčiau Maxi Bag su trumpesniu dirželiu ir tamsesne oda…', send: 'Siųsti užsakymą', sending: 'Siunčiama…', ok: 'Ačiū! Jūsų užsakymas gautas. Atsakymą matysite šio puslapio viršuje, tiesiog sugrįžkite į svetainę.', error: 'Nepavyko išsiųsti. Bandykite dar kartą.', errName: 'Įrašykite savo vardą.', errEmail: 'Įrašykite teisingą el. pašto adresą arba palikite laukelį tuščią.', errDetails: 'Aprašykite savo užsakymą.', emailHint: 'Nebūtina. Pokalbį galima tęsti čia, svetainėje.' },
    conversation: { title: 'Jūsų pokalbis su SLOU', lead: 'Čia matysite mano atsakymus. Sugrįžkite į šį puslapį bet kada, pokalbis išsaugotas šioje naršyklėje.', you: 'Jūs', shop: 'SLOU', waiting: 'Atsakysiu kuo greičiau, užsukite vėliau.', placeholder: 'Parašykite žinutę…', send: 'Siųsti', sending: 'Siunčiama…', error: 'Nepavyko išsiųsti. Bandykite dar kartą.', empty: 'Parašykite žinutę.', delete: 'Ištrinti pokalbį', deleteConfirm: 'Ar tikrai ištrinti šį pokalbį? Jis dings iš šio puslapio.', deleteError: 'Nepavyko ištrinti. Bandykite dar kartą.' },
    xmas: { eyebrow: 'Kalėdinis pasiūlymas', title: 'Kalėdinės dovanos su asmenine žinute', lead: 'Visus gaminius galima personalizuoti: išspausime raides, vardą, žodį ar datą.', wallet: 'Card wallet', walletDesc: 'Plona piniginė kortelėms iš augalinio rauginimo odos.', keys: 'Raktų pakabukai', keysDesc: 'Odiniai pakabukai su vardu, žodžiu ar data. Dovana šeimai, kolegoms ar šventės svečiams.', bulk: 'Nuo 10 vnt.', each: '/ vnt.', engrave: 'Su išspaustomis raidėmis', cta: 'Užsakyti', prefill: 'Kalėdinis pasiūlymas: {name}\nKiekis: \nIšspausti užrašą: ', photos: 'Daugiau nuotraukų', close: 'Uždaryti', expand: 'Išdidinti', was: 'Buvo', now: 'Dabar' },
    product: { order: 'Užsisakyti el. paštu', back: '← Į pradžią', handmade: 'Rankų darbo · natūrali augalinio rauginimo oda', production: 'Gamyba trunka iki 7–14 darbo dienų' },
    footer: { about: 'Rankų darbo odos gaminiai iš natūralios, augaliniu būdu raugintos odos. Gimstantys ne skubant, o iš lėto.', colShop: 'Parduotuvė', colInfo: 'Informacija', all: 'Visos prekės', wallets: 'Piniginės', bags: 'Rankinės', keys: 'Raktų aksesuarai', contacts: 'Kontaktai', returns: 'Pristatymas ir grąžinimas', privacy: 'Privatumo politika', cookies: 'Slapukų politika', rights: 'Visos teisės saugomos' },
    contacts: { kicker: 'Kontaktai', title: 'Parašykite mums', lead: 'Turite klausimų? Norite pasitarti dėl gaminio ar tiesiog pasisveikinti? Parašykite – atsakysiu kuo greičiau.', write: 'Rašyti el. laišką', toHome: 'Į pradžią', infoTitle: 'Kontaktinė informacija', i1: 'El. paštas:', i2: 'Gamyba: rankų darbo, iki 7–14 darbo dienų', i3: 'Pristatymas: Lietuva ir tarptautinis (susitarus)', form: { title: 'Parašykite žinutę', name: 'Vardas', email: 'El. paštas', message: 'Žinutė', send: 'Siųsti', sending: 'Siunčiama…', ok: 'Ačiū! Jūsų žinutė išsiųsta.', error: 'Nepavyko išsiųsti. Bandykite dar kartą.', close: 'Uždaryti' } },
    returns: { kicker: 'Sąlygos', title: 'Pristatymo ir grąžinimo sąlygos', h1: 'Gamybos terminas', p1: 'Kiekvienas SLOU gaminys – tai rankomis sukurtas daiktas, gimstantis ne skubant, o iš lėto. Daugelis prekių gaminamos tik po užsakymo, todėl gamyba gali užtrukti iki 7 darbo dienų, priklausomai nuo užimtumo. Dėkojame už kantrybę – lėtumas mūsų filosofijoje reiškia kokybę.', h2: 'Pristatymas Lietuvoje', p2: 'Kai tik gaminys bus paruoštas, jį išsiųsime jūsų pasirinktu būdu. Pristatymas trunka 1–3 darbo dienas nuo išsiuntimo. Apie siuntos išsiuntimą informuosime el. paštu.', h3: 'Tarptautinis pristatymas', p3a: 'Jeigu norėtumėte užsisakyti į užsienį – parašykite mums el. paštu ', p3b: ' ir mielai pasiūlysime individualų sprendimą.', h4: 'Grąžinimas', p4: 'Jeigu prekė netiko ar tiesiog apsigalvojote – turite teisę ją grąžinti per 14 kalendorinių dienų. Dėl grąžinimo susisiekite el. paštu ir suderinsime patogiausią būdą.' },
    privacy: { kicker: 'Privatumas', title: 'Privatumo politika', lead: 'Svetainė www.slou.lt (toliau – „Svetainė“) yra valdoma prekės ženklo SLOU. Mums rūpi Jūsų privatumas, todėl šioje Privatumo politikoje paaiškinama, kokius asmens duomenis renkame, kaip juos naudojame ir kokias teises turite.', h1: '1. Kokius duomenis renkame?', p1: 'Vardą, kontaktinius duomenis (el. paštą, telefoną), pristatymo adresą ir užsakymo informaciją.', h2: '2. Kaip naudojame Jūsų duomenis?', p2: 'Užsakymams vykdyti, su Jumis susisiekti dėl užsakymo ir teisės aktų reikalavimams įvykdyti.', h3: '3. Slapukai', p3a: 'Svetainėje naudojame slapukus, kurie padeda užtikrinti sklandų veikimą. Daugiau – ', p3link: 'Slapukų politikoje', p3b: '. Slapukus galite ištrinti ar išjungti savo naršyklės nustatymuose.', h4: '4. Duomenų saugojimas', p4: 'Jūsų duomenis saugome tiek, kiek būtina užsakymui įvykdyti ar įstatymais numatytiems reikalavimams (pvz., buhalterijai). Po to duomenys ištrinami arba anonimizuojami.', h5: '5. Jūsų teisės', p5a: 'Turite teisę susipažinti su savo duomenimis, prašyti juos ištaisyti ar ištrinti. Dėl to kreipkitės el. paštu ', p5b: '.' },
    cookies: { kicker: 'Slapukai', title: 'Slapukų politika', lead: 'Svetainė www.slou.lt naudoja slapukus (angl. „cookies“), kad pagerintų Jūsų naršymo patirtį ir užtikrintų sklandų svetainės veikimą.', h1: 'Kas yra slapukai?', p1: 'Slapukai – tai nedideli tekstiniai failai, kurie įrašomi į Jūsų įrenginį naršant svetainėje. Jie padeda svetainei atpažinti Jūsų įrenginį, įsiminti pasirinkimus ir suprasti, kaip naudojatės svetaine.', h2: 'Kaip valdyti slapukus?', p2: 'Jūs galite valdyti ar ištrinti slapukus per savo naršyklės nustatymus. Dauguma naršyklių leidžia:', li1: 'peržiūrėti įrašytus slapukus ir juos ištrinti;', li2: 'blokuoti trečiųjų šalių slapukus;', li3: 'blokuoti slapukus iš konkrečių svetainių.', p3: 'Atkreipkite dėmesį: išjungus slapukus, dalis svetainės funkcijų gali neveikti tinkamai. Slapukus naudojame teisėtu pagrindu – siekdami užtikrinti tinkamą svetainės veikimą.' }
  },

  en: {
    langLabel: 'EN', htmlLang: 'en',
    topbar: 'Handmade · Vegetable-tanned leather · Made in Lithuania',
    nav: { home: 'Home', shop: 'Shop', contacts: 'Contact' },
    titles: { home: 'SLOU — bags, key accessories, wallets', shop: 'Shop — SLOU', contacts: 'Contact — SLOU', returns: 'Shipping & Returns — SLOU', privacy: 'Privacy Policy — SLOU', cookies: 'Cookie Policy — SLOU' },
    hero: { eyebrow: 'Handmade leather', title: 'Things born slowly', tag: 'bags · key accessories · wallets', lead: 'Every SLOU piece is made by hand from natural, vegetable-tanned leather. Not in a hurry, but with care.', cta: 'Explore the shop' },
    features: [ { t: 'Handmade', d: 'Every detail is stitched and shaped by hand.' }, { t: 'Vegetable-tanned leather', d: 'Natural, ages beautifully, gains a patina.' }, { t: 'Unlined', d: 'Minimalist, durable construction.' }, { t: 'Made to order', d: 'Up to 7–14 working days, in Lithuania.' } ],
    shop: { eyebrow: 'Collection', title: 'Shop', sub: 'Hand-stitched pieces for everyday.', subLong: 'Hand-stitched pieces in vegetable-tanned leather, made to order.', all: 'All products' },
    ctaband: { title: 'Have a question?', text: 'Want to discuss a piece or order a custom solution? Write to us — we reply as soon as we can.', cta: 'Get in touch' },
    videos: { sound: 'Turn sound on / off', play: 'Play video', progress: 'Video progress', full: 'Fullscreen' },
    order: { eyebrow: 'Order', title: 'Create your order', lead: 'Describe what you would like: the piece, the leather colour, the size, an engraving or something entirely your own. I will reply right here on the website. Come back and you will see our conversation at the top of the page.', name: 'Name', email: 'Email (optional)', details: 'Your order', placeholder: 'For example: I would like the Maxi Bag with a shorter strap and darker leather…', send: 'Send order', sending: 'Sending…', ok: 'Thank you! Your order has been received. You will see my reply at the top of this page, just come back to the website.', error: 'Could not send. Please try again.', errName: 'Please enter your name.', errEmail: 'Please enter a valid email address or leave the field empty.', errDetails: 'Please describe your order.', emailHint: 'Optional. We can continue the conversation here on the website.' },
    conversation: { title: 'Your conversation with SLOU', lead: 'My replies will appear here. Come back to this page any time, the conversation is saved in this browser.', you: 'You', shop: 'SLOU', waiting: 'I will reply as soon as I can, check back later.', placeholder: 'Write a message…', send: 'Send', sending: 'Sending…', error: 'Could not send. Please try again.', empty: 'Please write a message.', delete: 'Delete conversation', deleteConfirm: 'Delete this conversation? It will disappear from this page.', deleteError: 'Could not delete. Please try again.' },
    xmas: { eyebrow: 'Christmas offer', title: 'Christmas gifts with a personal touch', lead: 'Every piece can be personalised: we stamp letters, a name, a word or a date into the leather.', wallet: 'Card wallet', walletDesc: 'A slim card wallet in vegetable-tanned leather.', keys: 'Keychains', keysDesc: 'Leather keychains with a name, a word or a date. A gift for family, colleagues or party guests.', bulk: 'From 10 pcs', each: '/ pc', engrave: 'With engraved letters', cta: 'Order', prefill: 'Christmas offer: {name}\nQuantity: \nEngraving: ', photos: 'More photos', close: 'Close', expand: 'Enlarge', was: 'Was', now: 'Now' },
    product: { order: 'Order by email', back: '← Back to home', handmade: 'Handmade · natural vegetable-tanned leather', production: 'Production takes up to 7–14 working days' },
    footer: { about: 'Handmade leather goods from natural, vegetable-tanned leather. Born not in a hurry, but slowly.', colShop: 'Shop', colInfo: 'Information', all: 'All products', wallets: 'Wallets', bags: 'Bags', keys: 'Key accessories', contacts: 'Contact', returns: 'Shipping & returns', privacy: 'Privacy policy', cookies: 'Cookie policy', rights: 'All rights reserved' },
    contacts: { kicker: 'Contact', title: 'Write to us', lead: 'Have a question? Want to discuss a piece or simply say hello? Write to us — we reply as soon as we can.', write: 'Send an email', toHome: 'To the homepage', infoTitle: 'Contact information', i1: 'Email:', i2: 'Production: handmade, up to 7–14 working days', i3: 'Shipping: Lithuania and international (on request)', form: { title: 'Write a message', name: 'Name', email: 'Email', message: 'Message', send: 'Send', sending: 'Sending…', ok: 'Thank you! Your message has been sent.', error: 'Could not send. Please try again.', close: 'Close' } },
    returns: { kicker: 'Terms', title: 'Shipping & Returns', h1: 'Production time', p1: 'Every SLOU piece is made by hand, born not in a hurry but slowly. Most items are made only to order, so production can take up to 7 working days depending on the workload. Thank you for your patience — in our philosophy, slowness means quality.', h2: 'Shipping in Lithuania', p2: 'As soon as the item is ready, we ship it by your chosen method. Delivery takes 1–3 working days from dispatch. We will notify you by email once it is sent.', h3: 'International shipping', p3a: 'If you would like to order abroad — write to us at ', p3b: ' and we will gladly offer an individual solution.', h4: 'Returns', p4: 'If an item did not fit or you simply changed your mind — you have the right to return it within 14 calendar days. For returns, contact us by email and we will arrange the most convenient way.' },
    privacy: { kicker: 'Privacy', title: 'Privacy Policy', lead: 'The website www.slou.lt (the “Website”) is managed by the SLOU brand. We care about your privacy, so this Privacy Policy explains what personal data we collect, how we use it and what rights you have.', h1: '1. What data do we collect?', p1: 'Name, contact details (email, phone), delivery address and order information.', h2: '2. How do we use your data?', p2: 'To fulfil orders, to contact you about your order and to meet legal requirements.', h3: '3. Cookies', p3a: 'We use cookies on the Website to ensure smooth operation. Learn more in the ', p3link: 'Cookie Policy', p3b: '. You can delete or disable cookies in your browser settings.', h4: '4. Data retention', p4: 'We store your data only as long as necessary to fulfil an order or to meet statutory requirements (e.g. accounting). After that, data is deleted or anonymised.', h5: '5. Your rights', p5a: 'You have the right to access your data and to request its correction or deletion. To do so, contact us at ', p5b: '.' },
    cookies: { kicker: 'Cookies', title: 'Cookie Policy', lead: 'The website www.slou.lt uses cookies to improve your browsing experience and ensure the website works smoothly.', h1: 'What are cookies?', p1: 'Cookies are small text files stored on your device while browsing the website. They help the website recognise your device, remember your choices and understand how you use the site.', h2: 'How to manage cookies?', p2: 'You can manage or delete cookies via your browser settings. Most browsers allow you to:', li1: 'view stored cookies and delete them;', li2: 'block third-party cookies;', li3: 'block cookies from specific websites.', p3: 'Please note: disabling cookies may cause some website features to stop working properly. We use cookies on a lawful basis — to ensure the website works properly.' }
  },

  pt: {
    langLabel: 'PT', htmlLang: 'pt',
    topbar: 'Feito à mão · Couro de curtimento vegetal · Fabricado na Lituânia',
    nav: { home: 'Início', shop: 'Loja', contacts: 'Contactos' },
    titles: { home: 'SLOU — bolsas, acessórios de chaves, carteiras', shop: 'Loja — SLOU', contacts: 'Contactos — SLOU', returns: 'Envio e devoluções — SLOU', privacy: 'Política de Privacidade — SLOU', cookies: 'Política de Cookies — SLOU' },
    hero: { eyebrow: 'Couro feito à mão', title: 'Objetos que nascem devagar', tag: 'bolsas · acessórios de chaves · carteiras', lead: 'Cada peça SLOU é um objeto feito à mão em couro natural de curtimento vegetal. Sem pressa, mas com cuidado.', cta: 'Ver a loja' },
    features: [ { t: 'Feito à mão', d: 'Cada detalhe é costurado e moldado à mão.' }, { t: 'Couro de curtimento vegetal', d: 'Natural, envelhece bem, ganha pátina.' }, { t: 'Sem forro', d: 'Construção minimalista e durável.' }, { t: 'Feito por encomenda', d: 'Até 7–14 dias úteis, na Lituânia.' } ],
    shop: { eyebrow: 'Coleção', title: 'Loja', sub: 'Peças costuradas à mão para o dia a dia.', subLong: 'Peças costuradas à mão em couro de curtimento vegetal, feitas por encomenda.', all: 'Todos os produtos' },
    ctaband: { title: 'Tem alguma pergunta?', text: 'Quer falar sobre uma peça ou encomendar uma solução personalizada? Escreva-nos — respondemos assim que pudermos.', cta: 'Contactar' },
    videos: { sound: 'Ligar / desligar o som', play: 'Reproduzir vídeo', progress: 'Progresso do vídeo', full: 'Ecrã inteiro' },
    order: { eyebrow: 'Encomenda', title: 'Crie a sua encomenda', lead: 'Descreva o que gostaria: a peça, a cor do couro, o tamanho, uma gravação ou algo totalmente seu. Responderei aqui mesmo, no site. Ao voltar, verá a nossa conversa no topo da página.', name: 'Nome', email: 'E-mail (opcional)', details: 'A sua encomenda', placeholder: 'Por exemplo: gostaria da Maxi Bag com alça mais curta e couro mais escuro…', send: 'Enviar encomenda', sending: 'A enviar…', ok: 'Obrigado! A sua encomenda foi recebida. Verá a minha resposta no topo desta página, basta voltar ao site.', error: 'Não foi possível enviar. Tente novamente.', errName: 'Introduza o seu nome.', errEmail: 'Introduza um endereço de e-mail válido ou deixe o campo vazio.', errDetails: 'Descreva a sua encomenda.', emailHint: 'Opcional. Podemos continuar a conversa aqui, no site.' },
    conversation: { title: 'A sua conversa com a SLOU', lead: 'As minhas respostas aparecerão aqui. Volte a esta página quando quiser, a conversa fica guardada neste navegador.', you: 'Você', shop: 'SLOU', waiting: 'Responderei assim que puder, volte mais tarde.', placeholder: 'Escreva uma mensagem…', send: 'Enviar', sending: 'A enviar…', error: 'Não foi possível enviar. Tente novamente.', empty: 'Escreva uma mensagem.', delete: 'Eliminar conversa', deleteConfirm: 'Eliminar esta conversa? Deixará de aparecer nesta página.', deleteError: 'Não foi possível eliminar. Tente novamente.' },
    xmas: { eyebrow: 'Oferta de Natal', title: 'Presentes de Natal com um toque pessoal', lead: 'Todas as peças podem ser personalizadas: gravamos letras, um nome, uma palavra ou uma data no couro.', wallet: 'Card wallet', walletDesc: 'Uma carteira fina para cartões em couro de curtimento vegetal.', keys: 'Porta-chaves', keysDesc: 'Porta-chaves em couro com um nome, uma palavra ou uma data. Um presente para a família, colegas ou convidados.', bulk: 'A partir de 10 un.', each: '/ un.', engrave: 'Com letras gravadas', cta: 'Encomendar', prefill: 'Oferta de Natal: {name}\nQuantidade: \nGravação: ', photos: 'Mais fotos', close: 'Fechar', expand: 'Ampliar', was: 'Antes', now: 'Agora' },
    product: { order: 'Encomendar por e-mail', back: '← Voltar ao início', handmade: 'Feito à mão · couro natural de curtimento vegetal', production: 'A produção demora até 7–14 dias úteis' },
    footer: { about: 'Artigos de couro feitos à mão em couro natural de curtimento vegetal. Nascidos sem pressa, devagar.', colShop: 'Loja', colInfo: 'Informação', all: 'Todos os produtos', wallets: 'Carteiras', bags: 'Bolsas', keys: 'Acessórios de chaves', contacts: 'Contactos', returns: 'Envio e devoluções', privacy: 'Política de privacidade', cookies: 'Política de cookies', rights: 'Todos os direitos reservados' },
    contacts: { kicker: 'Contactos', title: 'Escreva-nos', lead: 'Tem alguma pergunta? Quer falar sobre uma peça ou apenas dizer olá? Escreva-nos — respondemos assim que pudermos.', write: 'Enviar e-mail', toHome: 'Ir para o início', infoTitle: 'Informações de contacto', i1: 'E-mail:', i2: 'Produção: feita à mão, até 7–14 dias úteis', i3: 'Envio: Lituânia e internacional (sob consulta)', form: { title: 'Escreva uma mensagem', name: 'Nome', email: 'E-mail', message: 'Mensagem', send: 'Enviar', sending: 'A enviar…', ok: 'Obrigado! A sua mensagem foi enviada.', error: 'Não foi possível enviar. Tente novamente.', close: 'Fechar' } },
    returns: { kicker: 'Condições', title: 'Envio e devoluções', h1: 'Prazo de produção', p1: 'Cada peça SLOU é feita à mão, nascida sem pressa, devagar. A maioria dos artigos é feita apenas por encomenda, por isso a produção pode demorar até 7 dias úteis, consoante a carga de trabalho. Obrigado pela paciência — na nossa filosofia, a lentidão significa qualidade.', h2: 'Envio na Lituânia', p2: 'Assim que o artigo estiver pronto, enviamo-lo pelo método que escolher. A entrega demora 1–3 dias úteis após o envio. Avisamos por e-mail assim que for expedido.', h3: 'Envio internacional', p3a: 'Se quiser encomendar para o estrangeiro — escreva-nos para ', p3b: ' e teremos todo o gosto em propor uma solução individual.', h4: 'Devoluções', p4: 'Se um artigo não serviu ou simplesmente mudou de ideias — tem o direito de o devolver no prazo de 14 dias corridos. Para devoluções, contacte-nos por e-mail e combinaremos a forma mais conveniente.' },
    privacy: { kicker: 'Privacidade', title: 'Política de Privacidade', lead: 'O site www.slou.lt (o «Site») é gerido pela marca SLOU. Preocupamo-nos com a sua privacidade, por isso esta Política de Privacidade explica que dados pessoais recolhemos, como os utilizamos e que direitos tem.', h1: '1. Que dados recolhemos?', p1: 'Nome, dados de contacto (e-mail, telefone), morada de entrega e informação da encomenda.', h2: '2. Como utilizamos os seus dados?', p2: 'Para processar encomendas, contactá-lo sobre a sua encomenda e cumprir requisitos legais.', h3: '3. Cookies', p3a: 'Utilizamos cookies no Site para garantir um funcionamento fluido. Saiba mais na ', p3link: 'Política de Cookies', p3b: '. Pode eliminar ou desativar os cookies nas definições do seu navegador.', h4: '4. Conservação dos dados', p4: 'Conservamos os seus dados apenas durante o tempo necessário para processar uma encomenda ou cumprir requisitos legais (por exemplo, contabilidade). Depois disso, os dados são eliminados ou anonimizados.', h5: '5. Os seus direitos', p5a: 'Tem o direito de aceder aos seus dados e de solicitar a sua correção ou eliminação. Para tal, contacte-nos através de ', p5b: '.' },
    cookies: { kicker: 'Cookies', title: 'Política de Cookies', lead: 'O site www.slou.lt utiliza cookies para melhorar a sua experiência de navegação e garantir o funcionamento fluido do site.', h1: 'O que são cookies?', p1: 'Os cookies são pequenos ficheiros de texto guardados no seu dispositivo enquanto navega no site. Ajudam o site a reconhecer o seu dispositivo, a memorizar as suas escolhas e a compreender como utiliza o site.', h2: 'Como gerir os cookies?', p2: 'Pode gerir ou eliminar os cookies através das definições do seu navegador. A maioria dos navegadores permite:', li1: 'ver os cookies guardados e eliminá-los;', li2: 'bloquear cookies de terceiros;', li3: 'bloquear cookies de sites específicos.', p3: 'Atenção: desativar os cookies pode fazer com que algumas funcionalidades do site deixem de funcionar corretamente. Utilizamos cookies com base legítima — para garantir o correto funcionamento do site.' }
  },

  fr: {
    langLabel: 'FR', htmlLang: 'fr',
    topbar: 'Fait main · Cuir à tannage végétal · Fabriqué en Lituanie',
    nav: { home: 'Accueil', shop: 'Boutique', contacts: 'Contact' },
    titles: { home: 'SLOU — sacs, accessoires de clés, portefeuilles', shop: 'Boutique — SLOU', contacts: 'Contact — SLOU', returns: 'Livraison et retours — SLOU', privacy: 'Politique de confidentialité — SLOU', cookies: 'Politique de cookies — SLOU' },
    hero: { eyebrow: 'Cuir fait main', title: 'Des objets qui naissent lentement', tag: 'sacs · accessoires de clés · portefeuilles', lead: 'Chaque pièce SLOU est un objet fait main en cuir naturel à tannage végétal. Sans hâte, mais avec soin.', cta: 'Découvrir la boutique' },
    features: [ { t: 'Fait main', d: 'Chaque détail est cousu et façonné à la main.' }, { t: 'Cuir à tannage végétal', d: 'Naturel, vieillit bien, se patine.' }, { t: 'Sans doublure', d: 'Construction minimaliste et durable.' }, { t: 'Fabriqué sur commande', d: 'Jusqu’à 7–14 jours ouvrés, en Lituanie.' } ],
    shop: { eyebrow: 'Collection', title: 'Boutique', sub: 'Des pièces cousues à la main pour tous les jours.', subLong: 'Des pièces cousues à la main en cuir à tannage végétal, fabriquées sur commande.', all: 'Tous les produits' },
    ctaband: { title: 'Une question ?', text: 'Envie d’échanger sur une pièce ou de commander une solution sur mesure ? Écrivez-nous — nous répondons dès que possible.', cta: 'Nous contacter' },
    videos: { sound: 'Activer / désactiver le son', play: 'Lire la vidéo', progress: 'Progression de la vidéo', full: 'Plein écran' },
    order: { eyebrow: 'Commande', title: 'Composez votre commande', lead: 'Décrivez ce que vous souhaitez : la pièce, la couleur du cuir, la taille, une gravure ou une création entièrement personnelle. Je vous répondrai ici même, sur le site. En revenant, vous verrez notre conversation en haut de la page.', name: 'Nom', email: 'E-mail (facultatif)', details: 'Votre commande', placeholder: 'Par exemple : je voudrais le Maxi Bag avec une bandoulière plus courte et un cuir plus foncé…', send: 'Envoyer la commande', sending: 'Envoi…', ok: 'Merci ! Votre commande a bien été reçue. Vous verrez ma réponse en haut de cette page, revenez simplement sur le site.', error: 'L’envoi a échoué. Veuillez réessayer.', errName: 'Veuillez saisir votre nom.', errEmail: 'Veuillez saisir une adresse e-mail valide ou laisser le champ vide.', errDetails: 'Veuillez décrire votre commande.', emailHint: 'Facultatif. Nous pouvons poursuivre la conversation ici, sur le site.' },
    conversation: { title: 'Votre conversation avec SLOU', lead: 'Mes réponses apparaîtront ici. Revenez sur cette page quand vous voulez, la conversation est enregistrée dans ce navigateur.', you: 'Vous', shop: 'SLOU', waiting: 'Je vous répondrai dès que possible, revenez plus tard.', placeholder: 'Écrivez un message…', send: 'Envoyer', sending: 'Envoi…', error: 'L’envoi a échoué. Veuillez réessayer.', empty: 'Veuillez écrire un message.', delete: 'Supprimer la conversation', deleteConfirm: 'Supprimer cette conversation ? Elle disparaîtra de cette page.', deleteError: 'La suppression a échoué. Veuillez réessayer.' },
    xmas: { eyebrow: 'Offre de Noël', title: 'Des cadeaux de Noël personnalisés', lead: 'Chaque pièce peut être personnalisée : nous gravons des lettres, un prénom, un mot ou une date dans le cuir.', wallet: 'Card wallet', walletDesc: 'Un porte-cartes fin en cuir à tannage végétal.', keys: 'Porte-clés', keysDesc: 'Porte-clés en cuir avec un prénom, un mot ou une date. Un cadeau pour la famille, les collègues ou les invités.', bulk: 'Dès 10 pièces', each: '/ pièce', engrave: 'Avec lettres gravées', cta: 'Commander', prefill: 'Offre de Noël : {name}\nQuantité : \nGravure : ', photos: 'Plus de photos', close: 'Fermer', expand: 'Agrandir', was: 'Avant', now: 'Maintenant' },
    product: { order: 'Commander par e-mail', back: '← Retour à l’accueil', handmade: 'Fait main · cuir naturel à tannage végétal', production: 'La fabrication prend jusqu’à 7–14 jours ouvrés' },
    footer: { about: 'Articles en cuir faits main, en cuir naturel à tannage végétal. Nés sans hâte, lentement.', colShop: 'Boutique', colInfo: 'Informations', all: 'Tous les produits', wallets: 'Portefeuilles', bags: 'Sacs', keys: 'Accessoires de clés', contacts: 'Contact', returns: 'Livraison et retours', privacy: 'Politique de confidentialité', cookies: 'Politique de cookies', rights: 'Tous droits réservés' },
    contacts: { kicker: 'Contact', title: 'Écrivez-nous', lead: 'Une question ? Envie d’échanger sur une pièce ou simplement de dire bonjour ? Écrivez-nous — nous répondons dès que possible.', write: 'Envoyer un e-mail', toHome: 'Aller à l’accueil', infoTitle: 'Coordonnées', i1: 'E-mail :', i2: 'Fabrication : faite main, jusqu’à 7–14 jours ouvrés', i3: 'Livraison : Lituanie et international (sur demande)', form: { title: 'Écrivez un message', name: 'Nom', email: 'E-mail', message: 'Message', send: 'Envoyer', sending: 'Envoi…', ok: 'Merci ! Votre message a été envoyé.', error: 'Échec de l’envoi. Veuillez réessayer.', close: 'Fermer' } },
    returns: { kicker: 'Conditions', title: 'Livraison et retours', h1: 'Délai de fabrication', p1: 'Chaque pièce SLOU est faite main, née sans hâte, lentement. La plupart des articles sont fabriqués uniquement sur commande, la fabrication peut donc prendre jusqu’à 7 jours ouvrés selon la charge de travail. Merci de votre patience — dans notre philosophie, la lenteur est gage de qualité.', h2: 'Livraison en Lituanie', p2: 'Dès que l’article est prêt, nous l’expédions selon le mode choisi. La livraison prend 1–3 jours ouvrés après l’expédition. Nous vous prévenons par e-mail dès l’envoi.', h3: 'Livraison internationale', p3a: 'Si vous souhaitez commander à l’étranger — écrivez-nous à ', p3b: ' et nous vous proposerons volontiers une solution individuelle.', h4: 'Retours', p4: 'Si un article ne convient pas ou si vous changez d’avis — vous avez le droit de le retourner sous 14 jours calendaires. Pour un retour, contactez-nous par e-mail et nous conviendrons de la façon la plus pratique.' },
    privacy: { kicker: 'Confidentialité', title: 'Politique de confidentialité', lead: 'Le site www.slou.lt (le « Site ») est géré par la marque SLOU. Votre vie privée nous tient à cœur ; cette Politique de confidentialité explique quelles données personnelles nous collectons, comment nous les utilisons et quels sont vos droits.', h1: '1. Quelles données collectons-nous ?', p1: 'Nom, coordonnées (e-mail, téléphone), adresse de livraison et informations de commande.', h2: '2. Comment utilisons-nous vos données ?', p2: 'Pour traiter les commandes, vous contacter à propos de votre commande et respecter les obligations légales.', h3: '3. Cookies', p3a: 'Nous utilisons des cookies sur le Site pour garantir son bon fonctionnement. En savoir plus dans la ', p3link: 'Politique de cookies', p3b: '. Vous pouvez supprimer ou désactiver les cookies dans les paramètres de votre navigateur.', h4: '4. Conservation des données', p4: 'Nous conservons vos données uniquement le temps nécessaire au traitement d’une commande ou au respect des obligations légales (par exemple, la comptabilité). Ensuite, les données sont supprimées ou anonymisées.', h5: '5. Vos droits', p5a: 'Vous avez le droit d’accéder à vos données et d’en demander la rectification ou la suppression. Pour cela, contactez-nous à ', p5b: '.' },
    cookies: { kicker: 'Cookies', title: 'Politique de cookies', lead: 'Le site www.slou.lt utilise des cookies pour améliorer votre expérience de navigation et assurer le bon fonctionnement du site.', h1: 'Que sont les cookies ?', p1: 'Les cookies sont de petits fichiers texte enregistrés sur votre appareil lors de la navigation. Ils aident le site à reconnaître votre appareil, à mémoriser vos choix et à comprendre comment vous l’utilisez.', h2: 'Comment gérer les cookies ?', p2: 'Vous pouvez gérer ou supprimer les cookies via les paramètres de votre navigateur. La plupart des navigateurs permettent de :', li1: 'consulter les cookies enregistrés et les supprimer ;', li2: 'bloquer les cookies tiers ;', li3: 'bloquer les cookies de sites spécifiques.', p3: 'Remarque : la désactivation des cookies peut empêcher certaines fonctionnalités du site de fonctionner correctement. Nous utilisons des cookies sur une base légale — pour assurer le bon fonctionnement du site.' }
  },

  de: {
    langLabel: 'DE', htmlLang: 'de',
    topbar: 'Handarbeit · Pflanzlich gegerbtes Leder · Hergestellt in Litauen',
    nav: { home: 'Start', shop: 'Shop', contacts: 'Kontakt' },
    titles: { home: 'SLOU — Taschen, Schlüsselaccessoires, Portemonnaies', shop: 'Shop — SLOU', contacts: 'Kontakt — SLOU', returns: 'Versand & Rückgabe — SLOU', privacy: 'Datenschutzerklärung — SLOU', cookies: 'Cookie-Richtlinie — SLOU' },
    hero: { eyebrow: 'Handgemachtes Leder', title: 'Dinge, die langsam entstehen', tag: 'Taschen · Schlüsselaccessoires · Portemonnaies', lead: 'Jedes SLOU-Stück ist ein von Hand gefertigtes Objekt aus natürlichem, pflanzlich gegerbtem Leder. Nicht in Eile, sondern mit Sorgfalt.', cta: 'Zum Shop' },
    features: [ { t: 'Handarbeit', d: 'Jedes Detail wird von Hand genäht und geformt.' }, { t: 'Pflanzlich gegerbtes Leder', d: 'Natürlich, altert schön, bekommt Patina.' }, { t: 'Ungefüttert', d: 'Minimalistische, langlebige Konstruktion.' }, { t: 'Auf Bestellung gefertigt', d: 'Bis zu 7–14 Werktage, in Litauen.' } ],
    shop: { eyebrow: 'Kollektion', title: 'Shop', sub: 'Handgenähte Stücke für jeden Tag.', subLong: 'Handgenähte Stücke aus pflanzlich gegerbtem Leder, auf Bestellung gefertigt.', all: 'Alle Produkte' },
    ctaband: { title: 'Haben Sie Fragen?', text: 'Möchten Sie über ein Stück sprechen oder eine individuelle Lösung bestellen? Schreiben Sie uns — wir antworten so schnell wie möglich.', cta: 'Kontakt aufnehmen' },
    videos: { sound: 'Ton ein- / ausschalten', play: 'Video abspielen', progress: 'Videofortschritt', full: 'Vollbild' },
    order: { eyebrow: 'Bestellung', title: 'Stellen Sie Ihre Bestellung zusammen', lead: 'Beschreiben Sie, was Sie sich wünschen: das Stück, die Lederfarbe, die Größe, eine Gravur oder etwas ganz Eigenes. Ich antworte direkt hier auf der Website. Wenn Sie wiederkommen, sehen Sie unser Gespräch oben auf der Seite.', name: 'Name', email: 'E-Mail (optional)', details: 'Ihre Bestellung', placeholder: 'Zum Beispiel: Ich hätte gern die Maxi Bag mit kürzerem Riemen und dunklerem Leder…', send: 'Bestellung senden', sending: 'Wird gesendet…', ok: 'Danke! Ihre Bestellung ist eingegangen. Meine Antwort sehen Sie oben auf dieser Seite, kommen Sie einfach wieder auf die Website.', error: 'Senden fehlgeschlagen. Bitte versuchen Sie es erneut.', errName: 'Bitte geben Sie Ihren Namen ein.', errEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein oder lassen Sie das Feld leer.', errDetails: 'Bitte beschreiben Sie Ihre Bestellung.', emailHint: 'Optional. Wir können das Gespräch hier auf der Website fortsetzen.' },
    conversation: { title: 'Ihr Gespräch mit SLOU', lead: 'Meine Antworten erscheinen hier. Kommen Sie jederzeit auf diese Seite zurück, das Gespräch ist in diesem Browser gespeichert.', you: 'Sie', shop: 'SLOU', waiting: 'Ich antworte so schnell wie möglich, schauen Sie später wieder vorbei.', placeholder: 'Nachricht schreiben…', send: 'Senden', sending: 'Wird gesendet…', error: 'Senden fehlgeschlagen. Bitte versuchen Sie es erneut.', empty: 'Bitte schreiben Sie eine Nachricht.', delete: 'Gespräch löschen', deleteConfirm: 'Dieses Gespräch löschen? Es verschwindet von dieser Seite.', deleteError: 'Löschen fehlgeschlagen. Bitte versuchen Sie es erneut.' },
    xmas: { eyebrow: 'Weihnachtsangebot', title: 'Weihnachtsgeschenke mit persönlicher Note', lead: 'Jedes Stück lässt sich personalisieren: Wir prägen Buchstaben, einen Namen, ein Wort oder ein Datum ins Leder.', wallet: 'Card wallet', walletDesc: 'Ein schlankes Kartenetui aus pflanzlich gegerbtem Leder.', keys: 'Schlüsselanhänger', keysDesc: 'Lederanhänger mit Namen, Wort oder Datum. Ein Geschenk für Familie, Kollegen oder Gäste.', bulk: 'Ab 10 Stück', each: '/ Stück', engrave: 'Mit geprägten Buchstaben', cta: 'Bestellen', prefill: 'Weihnachtsangebot: {name}\nMenge: \nPrägung: ', photos: 'Weitere Fotos', close: 'Schließen', expand: 'Vergrößern', was: 'Vorher', now: 'Jetzt' },
    product: { order: 'Per E-Mail bestellen', back: '← Zurück zur Startseite', handmade: 'Handarbeit · natürliches, pflanzlich gegerbtes Leder', production: 'Die Fertigung dauert bis zu 7–14 Werktage' },
    footer: { about: 'Handgefertigte Lederwaren aus natürlichem, pflanzlich gegerbtem Leder. Nicht in Eile entstanden, sondern langsam.', colShop: 'Shop', colInfo: 'Informationen', all: 'Alle Produkte', wallets: 'Portemonnaies', bags: 'Taschen', keys: 'Schlüsselaccessoires', contacts: 'Kontakt', returns: 'Versand & Rückgabe', privacy: 'Datenschutz', cookies: 'Cookie-Richtlinie', rights: 'Alle Rechte vorbehalten' },
    contacts: { kicker: 'Kontakt', title: 'Schreiben Sie uns', lead: 'Haben Sie eine Frage? Möchten Sie über ein Stück sprechen oder einfach Hallo sagen? Schreiben Sie uns — wir antworten so schnell wie möglich.', write: 'E-Mail senden', toHome: 'Zur Startseite', infoTitle: 'Kontaktinformationen', i1: 'E-Mail:', i2: 'Fertigung: Handarbeit, bis zu 7–14 Werktage', i3: 'Versand: Litauen und international (auf Anfrage)', form: { title: 'Schreiben Sie eine Nachricht', name: 'Name', email: 'E-Mail', message: 'Nachricht', send: 'Senden', sending: 'Senden…', ok: 'Danke! Ihre Nachricht wurde gesendet.', error: 'Senden fehlgeschlagen. Bitte erneut versuchen.', close: 'Schließen' } },
    returns: { kicker: 'Bedingungen', title: 'Versand & Rückgabe', h1: 'Fertigungszeit', p1: 'Jedes SLOU-Stück wird von Hand gefertigt, nicht in Eile, sondern langsam. Die meisten Artikel werden nur auf Bestellung gefertigt, daher kann die Fertigung je nach Auslastung bis zu 7 Werktage dauern. Danke für Ihre Geduld — in unserer Philosophie bedeutet Langsamkeit Qualität.', h2: 'Versand in Litauen', p2: 'Sobald der Artikel fertig ist, versenden wir ihn auf dem von Ihnen gewählten Weg. Die Lieferung dauert 1–3 Werktage ab Versand. Wir benachrichtigen Sie per E-Mail, sobald er verschickt ist.', h3: 'Internationaler Versand', p3a: 'Wenn Sie ins Ausland bestellen möchten — schreiben Sie uns an ', p3b: ' und wir bieten Ihnen gerne eine individuelle Lösung an.', h4: 'Rückgabe', p4: 'Wenn ein Artikel nicht passt oder Sie es sich anders überlegt haben — haben Sie das Recht, ihn innerhalb von 14 Kalendertagen zurückzugeben. Kontaktieren Sie uns für die Rückgabe per E-Mail, und wir vereinbaren den bequemsten Weg.' },
    privacy: { kicker: 'Datenschutz', title: 'Datenschutzerklärung', lead: 'Die Website www.slou.lt (die „Website“) wird von der Marke SLOU betrieben. Ihre Privatsphäre ist uns wichtig, daher erläutert diese Datenschutzerklärung, welche personenbezogenen Daten wir erheben, wie wir sie verwenden und welche Rechte Sie haben.', h1: '1. Welche Daten erheben wir?', p1: 'Name, Kontaktdaten (E-Mail, Telefon), Lieferadresse und Bestellinformationen.', h2: '2. Wie verwenden wir Ihre Daten?', p2: 'Zur Abwicklung von Bestellungen, zur Kontaktaufnahme bezüglich Ihrer Bestellung und zur Erfüllung gesetzlicher Anforderungen.', h3: '3. Cookies', p3a: 'Wir verwenden Cookies auf der Website, um einen reibungslosen Betrieb zu gewährleisten. Mehr dazu in der ', p3link: 'Cookie-Richtlinie', p3b: '. Sie können Cookies in den Einstellungen Ihres Browsers löschen oder deaktivieren.', h4: '4. Datenspeicherung', p4: 'Wir speichern Ihre Daten nur so lange, wie es zur Abwicklung einer Bestellung oder zur Erfüllung gesetzlicher Anforderungen (z. B. Buchhaltung) erforderlich ist. Danach werden die Daten gelöscht oder anonymisiert.', h5: '5. Ihre Rechte', p5a: 'Sie haben das Recht, auf Ihre Daten zuzugreifen und deren Berichtigung oder Löschung zu verlangen. Kontaktieren Sie uns dazu unter ', p5b: '.' },
    cookies: { kicker: 'Cookies', title: 'Cookie-Richtlinie', lead: 'Die Website www.slou.lt verwendet Cookies, um Ihr Surferlebnis zu verbessern und einen reibungslosen Betrieb der Website zu gewährleisten.', h1: 'Was sind Cookies?', p1: 'Cookies sind kleine Textdateien, die beim Surfen auf Ihrem Gerät gespeichert werden. Sie helfen der Website, Ihr Gerät zu erkennen, Ihre Auswahl zu speichern und zu verstehen, wie Sie die Website nutzen.', h2: 'Wie verwaltet man Cookies?', p2: 'Sie können Cookies über die Einstellungen Ihres Browsers verwalten oder löschen. Die meisten Browser ermöglichen es Ihnen:', li1: 'gespeicherte Cookies anzuzeigen und zu löschen;', li2: 'Cookies von Drittanbietern zu blockieren;', li3: 'Cookies bestimmter Websites zu blockieren.', p3: 'Hinweis: Das Deaktivieren von Cookies kann dazu führen, dass einige Funktionen der Website nicht mehr richtig funktionieren. Wir verwenden Cookies auf rechtmäßiger Grundlage — um den ordnungsgemäßen Betrieb der Website zu gewährleisten.' }
  },

  es: {
    langLabel: 'ES', htmlLang: 'es',
    topbar: 'Hecho a mano · Cuero de curtido vegetal · Fabricado en Lituania',
    nav: { home: 'Inicio', shop: 'Tienda', contacts: 'Contacto' },
    titles: { home: 'SLOU — bolsos, accesorios de llaves, carteras', shop: 'Tienda — SLOU', contacts: 'Contacto — SLOU', returns: 'Envío y devoluciones — SLOU', privacy: 'Política de Privacidad — SLOU', cookies: 'Política de Cookies — SLOU' },
    hero: { eyebrow: 'Cuero hecho a mano', title: 'Objetos que nacen despacio', tag: 'bolsos · accesorios de llaves · carteras', lead: 'Cada pieza SLOU es un objeto hecho a mano en cuero natural de curtido vegetal. Sin prisa, pero con cuidado.', cta: 'Ver la tienda' },
    features: [ { t: 'Hecho a mano', d: 'Cada detalle se cose y se moldea a mano.' }, { t: 'Cuero de curtido vegetal', d: 'Natural, envejece bien, gana pátina.' }, { t: 'Sin forro', d: 'Construcción minimalista y duradera.' }, { t: 'Hecho por encargo', d: 'Hasta 7–14 días laborables, en Lituania.' } ],
    shop: { eyebrow: 'Colección', title: 'Tienda', sub: 'Piezas cosidas a mano para el día a día.', subLong: 'Piezas cosidas a mano en cuero de curtido vegetal, hechas por encargo.', all: 'Todos los productos' },
    ctaband: { title: '¿Tienes alguna pregunta?', text: '¿Quieres hablar sobre una pieza o encargar una solución personalizada? Escríbenos: respondemos lo antes posible.', cta: 'Contactar' },
    videos: { sound: 'Activar / desactivar el sonido', play: 'Reproducir vídeo', progress: 'Progreso del vídeo', full: 'Pantalla completa' },
    order: { eyebrow: 'Pedido', title: 'Crea tu pedido', lead: 'Describe lo que te gustaría: la pieza, el color del cuero, el tamaño, un grabado o algo totalmente tuyo. Te responderé aquí mismo, en la web. Cuando vuelvas, verás nuestra conversación en la parte superior de la página.', name: 'Nombre', email: 'Correo electrónico (opcional)', details: 'Tu pedido', placeholder: 'Por ejemplo: me gustaría la Maxi Bag con correa más corta y cuero más oscuro…', send: 'Enviar pedido', sending: 'Enviando…', ok: '¡Gracias! Hemos recibido tu pedido. Verás mi respuesta en la parte superior de esta página, solo tienes que volver a la web.', error: 'No se pudo enviar. Inténtalo de nuevo.', errName: 'Introduce tu nombre.', errEmail: 'Introduce una dirección de correo válida o deja el campo vacío.', errDetails: 'Describe tu pedido.', emailHint: 'Opcional. Podemos continuar la conversación aquí, en la web.' },
    conversation: { title: 'Tu conversación con SLOU', lead: 'Mis respuestas aparecerán aquí. Vuelve a esta página cuando quieras, la conversación se guarda en este navegador.', you: 'Tú', shop: 'SLOU', waiting: 'Responderé lo antes posible, vuelve más tarde.', placeholder: 'Escribe un mensaje…', send: 'Enviar', sending: 'Enviando…', error: 'No se pudo enviar. Inténtalo de nuevo.', empty: 'Escribe un mensaje.', delete: 'Eliminar conversación', deleteConfirm: '¿Eliminar esta conversación? Desaparecerá de esta página.', deleteError: 'No se pudo eliminar. Inténtalo de nuevo.' },
    xmas: { eyebrow: 'Oferta de Navidad', title: 'Regalos de Navidad con un toque personal', lead: 'Todas las piezas se pueden personalizar: grabamos letras, un nombre, una palabra o una fecha en el cuero.', wallet: 'Card wallet', walletDesc: 'Una cartera fina para tarjetas en cuero de curtido vegetal.', keys: 'Llaveros', keysDesc: 'Llaveros de cuero con un nombre, una palabra o una fecha. Un regalo para la familia, compañeros o invitados.', bulk: 'Desde 10 uds.', each: '/ ud.', engrave: 'Con letras grabadas', cta: 'Pedir', prefill: 'Oferta de Navidad: {name}\nCantidad: \nGrabado: ', photos: 'Más fotos', close: 'Cerrar', expand: 'Ampliar', was: 'Antes', now: 'Ahora' },
    product: { order: 'Pedir por correo', back: '← Volver al inicio', handmade: 'Hecho a mano · cuero natural de curtido vegetal', production: 'La producción tarda hasta 7–14 días laborables' },
    footer: { about: 'Artículos de cuero hechos a mano en cuero natural de curtido vegetal. Nacidos sin prisa, despacio.', colShop: 'Tienda', colInfo: 'Información', all: 'Todos los productos', wallets: 'Carteras', bags: 'Bolsos', keys: 'Accesorios de llaves', contacts: 'Contacto', returns: 'Envío y devoluciones', privacy: 'Política de privacidad', cookies: 'Política de cookies', rights: 'Todos los derechos reservados' },
    contacts: { kicker: 'Contacto', title: 'Escríbenos', lead: '¿Tienes una pregunta? ¿Quieres hablar sobre una pieza o simplemente saludar? Escríbenos: respondemos lo antes posible.', write: 'Enviar un correo', toHome: 'Ir al inicio', infoTitle: 'Información de contacto', i1: 'Correo:', i2: 'Producción: hecha a mano, hasta 7–14 días laborables', i3: 'Envío: Lituania e internacional (a petición)', form: { title: 'Escribe un mensaje', name: 'Nombre', email: 'Correo', message: 'Mensaje', send: 'Enviar', sending: 'Enviando…', ok: '¡Gracias! Tu mensaje ha sido enviado.', error: 'No se pudo enviar. Inténtalo de nuevo.', close: 'Cerrar' } },
    returns: { kicker: 'Condiciones', title: 'Envío y devoluciones', h1: 'Plazo de producción', p1: 'Cada pieza SLOU está hecha a mano, nacida sin prisa, despacio. La mayoría de los artículos se hacen solo por encargo, por lo que la producción puede tardar hasta 7 días laborables según la carga de trabajo. Gracias por tu paciencia: en nuestra filosofía, la lentitud significa calidad.', h2: 'Envío en Lituania', p2: 'En cuanto el artículo esté listo, lo enviamos por el método que elijas. La entrega tarda 1–3 días laborables desde el envío. Te avisamos por correo en cuanto se envíe.', h3: 'Envío internacional', p3a: 'Si deseas hacer un pedido al extranjero, escríbenos a ', p3b: ' y con gusto te ofreceremos una solución individual.', h4: 'Devoluciones', p4: 'Si un artículo no te quedó bien o simplemente cambiaste de opinión, tienes derecho a devolverlo en un plazo de 14 días naturales. Para devoluciones, contáctanos por correo y acordaremos la forma más cómoda.' },
    privacy: { kicker: 'Privacidad', title: 'Política de Privacidad', lead: 'El sitio web www.slou.lt (el «Sitio») está gestionado por la marca SLOU. Nos importa tu privacidad, por eso esta Política de Privacidad explica qué datos personales recopilamos, cómo los usamos y qué derechos tienes.', h1: '1. ¿Qué datos recopilamos?', p1: 'Nombre, datos de contacto (correo, teléfono), dirección de entrega e información del pedido.', h2: '2. ¿Cómo usamos tus datos?', p2: 'Para gestionar pedidos, contactarte sobre tu pedido y cumplir requisitos legales.', h3: '3. Cookies', p3a: 'Usamos cookies en el Sitio para garantizar un funcionamiento fluido. Más información en la ', p3link: 'Política de Cookies', p3b: '. Puedes eliminar o desactivar las cookies en la configuración de tu navegador.', h4: '4. Conservación de datos', p4: 'Conservamos tus datos solo el tiempo necesario para gestionar un pedido o cumplir requisitos legales (por ejemplo, contabilidad). Después, los datos se eliminan o se anonimizan.', h5: '5. Tus derechos', p5a: 'Tienes derecho a acceder a tus datos y a solicitar su corrección o eliminación. Para ello, contáctanos en ', p5b: '.' },
    cookies: { kicker: 'Cookies', title: 'Política de Cookies', lead: 'El sitio web www.slou.lt utiliza cookies para mejorar tu experiencia de navegación y garantizar el buen funcionamiento del sitio.', h1: '¿Qué son las cookies?', p1: 'Las cookies son pequeños archivos de texto que se guardan en tu dispositivo mientras navegas por el sitio. Ayudan al sitio a reconocer tu dispositivo, recordar tus preferencias y entender cómo lo usas.', h2: '¿Cómo gestionar las cookies?', p2: 'Puedes gestionar o eliminar las cookies a través de la configuración de tu navegador. La mayoría de los navegadores permiten:', li1: 'ver las cookies almacenadas y eliminarlas;', li2: 'bloquear cookies de terceros;', li3: 'bloquear cookies de sitios específicos.', p3: 'Ten en cuenta: desactivar las cookies puede hacer que algunas funciones del sitio dejen de funcionar correctamente. Usamos cookies sobre una base legítima: para garantizar el correcto funcionamiento del sitio.' }
  },

  it: {
    langLabel: 'IT', htmlLang: 'it',
    topbar: 'Fatto a mano · Cuoio a concia vegetale · Prodotto in Lituania',
    nav: { home: 'Home', shop: 'Negozio', contacts: 'Contatti' },
    titles: { home: 'SLOU — borse, accessori per chiavi, portafogli', shop: 'Negozio — SLOU', contacts: 'Contatti — SLOU', returns: 'Spedizione e resi — SLOU', privacy: 'Informativa sulla privacy — SLOU', cookies: 'Informativa sui cookie — SLOU' },
    hero: { eyebrow: 'Pelle fatta a mano', title: 'Oggetti che nascono lentamente', tag: 'borse · accessori per chiavi · portafogli', lead: 'Ogni pezzo SLOU è un oggetto fatto a mano in cuoio naturale a concia vegetale. Senza fretta, ma con cura.', cta: 'Scopri il negozio' },
    features: [ { t: 'Fatto a mano', d: 'Ogni dettaglio è cucito e modellato a mano.' }, { t: 'Cuoio a concia vegetale', d: 'Naturale, invecchia bene, acquista patina.' }, { t: 'Senza fodera', d: 'Costruzione minimalista e durevole.' }, { t: 'Fatto su ordinazione', d: 'Fino a 7–14 giorni lavorativi, in Lituania.' } ],
    shop: { eyebrow: 'Collezione', title: 'Negozio', sub: 'Pezzi cuciti a mano per tutti i giorni.', subLong: 'Pezzi cuciti a mano in cuoio a concia vegetale, fatti su ordinazione.', all: 'Tutti i prodotti' },
    ctaband: { title: 'Hai una domanda?', text: 'Vuoi parlare di un pezzo o ordinare una soluzione su misura? Scrivici — rispondiamo il prima possibile.', cta: 'Contattaci' },
    videos: { sound: 'Attiva / disattiva l’audio', play: 'Riproduci video', progress: 'Avanzamento del video', full: 'Schermo intero' },
    order: { eyebrow: 'Ordine', title: 'Crea il tuo ordine', lead: 'Descrivi ciò che desideri: il pezzo, il colore del cuoio, la misura, un’incisione o qualcosa di completamente tuo. Ti risponderò qui, sul sito. Tornando, vedrai la nostra conversazione in cima alla pagina.', name: 'Nome', email: 'E-mail (facoltativa)', details: 'Il tuo ordine', placeholder: 'Per esempio: vorrei la Maxi Bag con tracolla più corta e cuoio più scuro…', send: 'Invia ordine', sending: 'Invio…', ok: 'Grazie! Il tuo ordine è stato ricevuto. Vedrai la mia risposta in cima a questa pagina, ti basta tornare sul sito.', error: 'Invio non riuscito. Riprova.', errName: 'Inserisci il tuo nome.', errEmail: 'Inserisci un indirizzo e-mail valido oppure lascia il campo vuoto.', errDetails: 'Descrivi il tuo ordine.', emailHint: 'Facoltativa. Possiamo continuare la conversazione qui, sul sito.' },
    conversation: { title: 'La tua conversazione con SLOU', lead: 'Le mie risposte appariranno qui. Torna su questa pagina quando vuoi, la conversazione è salvata in questo browser.', you: 'Tu', shop: 'SLOU', waiting: 'Risponderò il prima possibile, ricontrolla più tardi.', placeholder: 'Scrivi un messaggio…', send: 'Invia', sending: 'Invio…', error: 'Invio non riuscito. Riprova.', empty: 'Scrivi un messaggio.', delete: 'Elimina conversazione', deleteConfirm: 'Eliminare questa conversazione? Scomparirà da questa pagina.', deleteError: 'Eliminazione non riuscita. Riprova.' },
    xmas: { eyebrow: 'Offerta di Natale', title: 'Regali di Natale con un tocco personale', lead: 'Ogni pezzo può essere personalizzato: imprimiamo lettere, un nome, una parola o una data nel cuoio.', wallet: 'Card wallet', walletDesc: 'Un portacarte sottile in cuoio a concia vegetale.', keys: 'Portachiavi', keysDesc: 'Portachiavi in cuoio con un nome, una parola o una data. Un regalo per la famiglia, i colleghi o gli ospiti.', bulk: 'Da 10 pz.', each: '/ pz.', engrave: 'Con lettere incise', cta: 'Ordina', prefill: 'Offerta di Natale: {name}\nQuantità: \nIncisione: ', photos: 'Altre foto', close: 'Chiudi', expand: 'Ingrandisci', was: 'Prima', now: 'Ora' },
    product: { order: 'Ordina via e-mail', back: '← Torna alla home', handmade: 'Fatto a mano · cuoio naturale a concia vegetale', production: 'La produzione richiede fino a 7–14 giorni lavorativi' },
    footer: { about: 'Articoli in cuoio fatti a mano in cuoio naturale a concia vegetale. Nati senza fretta, lentamente.', colShop: 'Negozio', colInfo: 'Informazioni', all: 'Tutti i prodotti', wallets: 'Portafogli', bags: 'Borse', keys: 'Accessori per chiavi', contacts: 'Contatti', returns: 'Spedizione e resi', privacy: 'Privacy', cookies: 'Cookie', rights: 'Tutti i diritti riservati' },
    contacts: { kicker: 'Contatti', title: 'Scrivici', lead: 'Hai una domanda? Vuoi parlare di un pezzo o semplicemente salutarci? Scrivici — rispondiamo il prima possibile.', write: 'Invia un’e-mail', toHome: 'Vai alla home', infoTitle: 'Informazioni di contatto', i1: 'E-mail:', i2: 'Produzione: fatta a mano, fino a 7–14 giorni lavorativi', i3: 'Spedizione: Lituania e internazionale (su richiesta)', form: { title: 'Scrivi un messaggio', name: 'Nome', email: 'E-mail', message: 'Messaggio', send: 'Invia', sending: 'Invio…', ok: 'Grazie! Il tuo messaggio è stato inviato.', error: 'Invio non riuscito. Riprova.', close: 'Chiudi' } },
    returns: { kicker: 'Condizioni', title: 'Spedizione e resi', h1: 'Tempo di produzione', p1: 'Ogni pezzo SLOU è fatto a mano, nato senza fretta, lentamente. La maggior parte degli articoli è realizzata solo su ordinazione, quindi la produzione può richiedere fino a 7 giorni lavorativi a seconda del carico di lavoro. Grazie per la pazienza — nella nostra filosofia, la lentezza significa qualità.', h2: 'Spedizione in Lituania', p2: 'Appena l’articolo è pronto, lo spediamo con il metodo che scegli. La consegna richiede 1–3 giorni lavorativi dalla spedizione. Ti avvisiamo via e-mail una volta spedito.', h3: 'Spedizione internazionale', p3a: 'Se desideri ordinare all’estero — scrivici a ', p3b: ' e saremo lieti di proporti una soluzione individuale.', h4: 'Resi', p4: 'Se un articolo non andava bene o hai semplicemente cambiato idea — hai il diritto di restituirlo entro 14 giorni di calendario. Per i resi, contattaci via e-mail e concorderemo il modo più comodo.' },
    privacy: { kicker: 'Privacy', title: 'Informativa sulla privacy', lead: 'Il sito www.slou.lt (il «Sito») è gestito dal marchio SLOU. Teniamo alla tua privacy, quindi questa Informativa spiega quali dati personali raccogliamo, come li usiamo e quali diritti hai.', h1: '1. Quali dati raccogliamo?', p1: 'Nome, dati di contatto (e-mail, telefono), indirizzo di consegna e informazioni sull’ordine.', h2: '2. Come usiamo i tuoi dati?', p2: 'Per evadere gli ordini, contattarti riguardo al tuo ordine e adempiere agli obblighi di legge.', h3: '3. Cookie', p3a: 'Usiamo i cookie sul Sito per garantirne il corretto funzionamento. Scopri di più nell’', p3link: 'Informativa sui cookie', p3b: '. Puoi eliminare o disattivare i cookie nelle impostazioni del tuo browser.', h4: '4. Conservazione dei dati', p4: 'Conserviamo i tuoi dati solo per il tempo necessario a evadere un ordine o ad adempiere agli obblighi di legge (ad es. contabilità). Successivamente i dati vengono eliminati o resi anonimi.', h5: '5. I tuoi diritti', p5a: 'Hai il diritto di accedere ai tuoi dati e di chiederne la rettifica o la cancellazione. Per farlo, contattaci a ', p5b: '.' },
    cookies: { kicker: 'Cookie', title: 'Informativa sui cookie', lead: 'Il sito www.slou.lt utilizza i cookie per migliorare la tua esperienza di navigazione e garantire il corretto funzionamento del sito.', h1: 'Cosa sono i cookie?', p1: 'I cookie sono piccoli file di testo salvati sul tuo dispositivo durante la navigazione. Aiutano il sito a riconoscere il tuo dispositivo, a ricordare le tue scelte e a capire come usi il sito.', h2: 'Come gestire i cookie?', p2: 'Puoi gestire o eliminare i cookie tramite le impostazioni del tuo browser. La maggior parte dei browser consente di:', li1: 'visualizzare i cookie salvati ed eliminarli;', li2: 'bloccare i cookie di terze parti;', li3: 'bloccare i cookie di siti specifici.', p3: 'Nota: la disattivazione dei cookie può impedire il corretto funzionamento di alcune funzionalità del sito. Utilizziamo i cookie su base lecita — per garantire il corretto funzionamento del sito.' }
  }

};
